package com;
// Generated 9 Mar, 2020 4:03:26 PM by Hibernate Tools 4.3.1



/**
 * CustomerTable generated by hbm2java
 */
public class CustomerTable  implements java.io.Serializable {


     private Integer CId;
     private String CName;

    public CustomerTable() {
    }

    public CustomerTable(String CName) {
       this.CName = CName;
    }
   
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }
    public String getCName() {
        return this.CName;
    }
    
    public void setCName(String CName) {
        this.CName = CName;
    }




}


