package organisation;
// Generated 9 Mar, 2020 4:47:27 PM by Hibernate Tools 4.3.1





/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int empId;
     private String empName;
     private AddressTable addressTable;

    public Employee() {
    }

	
    public Employee(int empId) {
        this.empId = empId;
    }
    public Employee(int empId, String empName, AddressTable addressTable) {
       this.empId = empId;
       this.empName = empName;
       this.addressTable = addressTable;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public void setAddressTable(AddressTable addressTable){
        this.addressTable = addressTable;
    }


}


